[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finance-tracker"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["SQLAlchemy>=2.0", "alembic>=1.13"]

[tool.setuptools]
packages = ["finance_tracker"]
